# Generated by Django 5.1.2 on 2024-11-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0028_merge_20241104_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=5)),
            ],
        ),
    ]
