# Generated by Django 5.1.2 on 2024-11-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0029_userrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserRoles',
        ),
        migrations.AlterModelTable(
            name='userroles',
            table='UserRoles',
        ),
    ]
