# Generated by Django 5.1.3 on 2024-11-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0030_alter_notifications_notification_type'),
        ('pulse', '0031_remove_userroles_id_userroles_role_type_and_more'),
    ]

    operations = [
    ]
