# Generated by Django 5.1.3 on 2024-11-12 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0032_merge_20241112_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communities',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse.users'),
        ),
    ]
