# Generated by Django 5.1.3 on 2024-11-13 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0033_communities_approved_communities_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.communities'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('question_answered', 'New Answer'), ('answer_commented', 'New Comment'), ('question_upvoted', 'Answer Accepted'), ('answer_accepted', 'Mention'), ('mention', 'Vote Received'), ('community_accepted', 'Community Accepted'), ('community_rejected', 'Community Rejected')], max_length=20),
        ),
    ]
