# Generated by Django 5.1.3 on 2024-11-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0034_notifications_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='community_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
